#+OPTIONS: toc:nil
* Linux Tutor
  This program was designed to help individuals understand how to use Linux.
  The aim of this project is to create an interactive terminal program, that
  allows individuals learn how to use Linux Terminal programs. This program will
  help users of all levels; However, the goal will be aimed towards beginners at
  the beginning.
** Contributions
There is a scrum board located in the projects tab for what I am currently working on. 
** Milestones
*** Extensibility
    I want to extract the portions of the code that conduct system calls and
    create a template for other module classes to call when developing new
    features.  

    This will allow the program to offer extensibilty without destroying the
    core functionality. They template will allow other developers to create
    extensions without causing any major errors. System calls can sometimes
    cause potential issues, such as "rm -rf /". My API would look to avoid such
    disasters from happening

    DEADLINE: <07-25-2018>

*** Add Modules -Beginner, Git
    If I complete the API poriton of the code, I will start developing modules for LinuxTutor.

*** Beginner Module 
    Beginner Module will allow new users the ability to learn basic linux
    commands, and give a background about common terminal operations, such as
    cat somefile.txt | grep "[A-Z, a-z]"

    DEADLINE: <08-21-2018>

*** Git Commands
    Git module will allow people to learn git without having to read man pages,
    it will walk through setting up a git page, pushing to the branch, etc. 
    


    
** Installation

** Documentation
   Documentation for all aspects of this project have been added to the Documentation directory.
   
