#!/bin/bash
#Linux Tutor

# Gets the name of the current Current Directory
getCurrentDirectory=${PWD##*/}

# Handle printing the correct message for every Directory the user enters into.

[ $getCurrentDirectory = LinuxTutorDirectory ] && cat .LinuxTutorIntroduction.txt

[ $getCurrentDirectory = ROOT ] && cat .LinuxDirectoryROOT.txt

[ $getCurrentDirectory = bin ] && cat .LinuxDirectoryBin.txt

[ $getCurrentDirectory = boot ] && cat .LinuxDirectoryBoot.txt

[ $getCurrentDirectory = dev ]&& cat .LinuxDirectoryDev.txt

[ $getCurrentDirectory = etc ] && cat .LinuxDirectoryEtc.txt

[ $getCurrentDirectory = lib ]&& cat .LinuxDirectoryLib.txt

[ $getCurrentDirectory = media ] && cat .LinuxDirectoryMedia.txt

[ $getCurrentDirectory = mnt ]&& cat .LinuxDirectoryMnt.txt

[ $getCurrentDirectory = opt ]&& cat .LinuxDirectoryOpt.txt

[ $getCurrentDirectory = proc ]&& cat .LinuxDirectoryProc.txt

[ $getCurrentDirectory = root ]&& cat .LinuxDirectoryRoot.txt

[ $getCurrentDirectory = sbin ]&& cat .LinuxDirectorySbin.txt

[ $getCurrentDirectory = srv ]&& cat .LinuxDirectorySrv.txt

[ $getCurrentDirectory = tmp ]&& cat .LinuxDirectoryTmp.txt

[ $getCurrentDirectory = usr ]&& cat .LinuxDirectoryUsr.txt

[ $getCurrentDirectory = var ]&& cat .LinuxDirectoryVar.txt

[ $getCurrentDirectory = home ]&& cat .LinuxDirectoryHome.txt

[ $getCurrentDirectory = user1 ]&& cat .LinuxDirectoryUser1.txt

# Handles reading the last line of .bash_history


